[package]
name = "msc-tui"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "msc-tui"
path = "src/main.rs"

[dependencies]
msc-core = { path = "../core" }
color-eyre = "0.6.5"
ratatui = "0.29.0"
crossterm = "0.29.0"
ratatui-image = { version = "8.1.1", features = ["crossterm"] }
image = "0.25.9"
