[package]
name = "msc-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.13.1", features = ["tokio", "image"] }
msc-core = { path = "../core" }
image = "0.25.9"
blake3 = "1.8.2"
