[package]
name = "suno-core"
version = "0.1.0"
edition = "2024"

[dependencies]
kira = "0.11.0"
image = "0.25.9"
lofty = "0.22.4"
blake3 = { version = "1.8.2", features = ["serde", "mmap"] }
dashmap = "6.1.0"
rayon = "1.11.0"
rand = "0.9.2"
